title: Sekvens
author:
  name: Sekvens
  email: sekvenskollektiv@gmail.com
description: Sekvens kollektiv
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
include: ['_pages', '_events', '_artists', '_merchs', '_releases']

collections:
  pages:
    collections_dir: _pages
    output: true
    permalink: /:path

  news:
    collections_dir: _news
    output: true
    permalink: /:path

  events:
    collections_dir: _events
    output: true
    permalink: /:path

  artists:
    collections_dir: _artists
    output: true
    permalink: /:path

  releases:
    collections_dir: _releases
    output: true
    permalink: /:path

  merchs:
    collections_dir: _merchs
    output: true
    permalink: /:path
